### ISSUE TITLE
Handling envoy's StatsSink.config?

### ISSUE THREAD

**Issue by pcn** [stripe/skycfg#29]
Trying out skycfg with envoy, and I'm looking for some guidance on how to create the appropriate message to create the matching structure/configuration for this message:

https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/metrics/v2/stats.proto#L21-L41

which is:
```
message StatsSink {
  // The name of the stats sink to instantiate. The name must match a supported
  // stats sink. The built-in stats sinks are:
  //
  // * :ref:`envoy.statsd <envoy_api_msg_config.metrics.v2.StatsdSink>`
  // * :ref:`envoy.dog_statsd <envoy_api_msg_config.metrics.v2.DogStatsdSink>`
  // * :ref:`envoy.metrics_service <envoy_api_msg_config.metrics.v2.MetricsServiceConfig>`
  // * :ref:`envoy.stat_sinks.hystrix <envoy_api_msg_config.metrics.v2.HystrixSink>`
  //
  // Sinks optionally support tagged/multiple dimensional metrics.
  string name = 1;

  // Stats sink specific configuration which depends on the sink being instantiated. See
  // :ref:`StatsdSink <envoy_api_msg_config.metrics.v2.StatsdSink>` for an example.
  oneof config_type {
    google.protobuf.Struct config = 2;

    // [#not-implemented-hide:]
    google.protobuf.Any typed_config = 3;
  }
}
```
I'm not clear what the expected way of associating a specific sink with this is, now. So for e.g. if I do this:

```
    ss = v2_metrics.StatsSink(
        name="envoy.dog_statsd",
        typed_config=v2_metrics.DogStatsdSink(address=sink_address)
```
The result is:
```
spacey@masonjar:~/go/src/github.com/pcn/envoy-proto$ go build; ./envoy-proto hello.sky
panic: TypeError: value <envoy.config.metrics.v2.DogStatsdSink address:<socket_address:<protocol:UDP address:"127.0.0.1" port_value:8126 > > > (type `envoy.config.metrics.v2.DogStatsdSink') can't be assigned to type `google.protobuf.Any'.

goroutine 1 [running]:
main.main()
	/home/spacey/go/src/github.com/pcn/envoy-proto/main.go:73 +0x6e3
```

which tracks; they are different types. So I'm wondering how the `typed_config` `Any` (or the `config` `struct`?) would get set from the particular statsd message types?

**Comment by jmillikin** [comment]
Skycfg will eventually have a helper to marshal a message into an `Any`, but doesn't right now. If I remember correctly the Envoy config loader doesn't support `typed_config` yet, so even if `proto.marshal_any()` existed you'd have to use the `Struct` version.

For converting normal messages into a `Struct`, I've been using JSON as an intermediate because `Struct` has a special JSON representation. Something like this:

```python
pb = proto.package("google.protobuf")
def to_struct(msg):
    return proto.from_json(pb.Struct, proto.to_json(msg))

config = v2_metrics.DogStatsdSink(address=sink_address)
ss = v2_metrics.StatsSink(
    name = "envoy.dog_statsd",
    config = to_struct(config))
```

**Comment by pcn** [comment]
Interesting - thanks!

**Comment by pcn** [comment]
@jmillikin one further question - is that requiring a particular version or checkout?  I'm getting this error:

`panic: reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*types.Value`

**Comment by jmillikin** [comment]
I'll have to look into that error message more deeply after the holidays, sorry. There's obviously a missing type check (assignment should return TypeError rather than panic), but the underlying error may be some sort of GoGo compatibility issue since Envoy doesn't use the standard go-protobuf library.

**Comment by dilyevsky** [comment]
@pcn could you post an example skycfg message that causes this panic?

**Comment by pcn** [comment]
@dilyevsky  here you go

reproducer/main.go:
```go
package main

import (
	"context"
	"fmt"
	"reflect"

	docopt "github.com/docopt/docopt-go"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	"github.com/stripe/skycfg"
	yaml "gopkg.in/yaml.v2"

	gogo_proto "github.com/gogo/protobuf/proto"

	_ "github.com/envoyproxy/go-control-plane/envoy/admin/v2alpha"
	_ "github.com/envoyproxy/go-control-plane/envoy/api/v2"
	_ "github.com/envoyproxy/go-control-plane/envoy/config/bootstrap/v2"
)

type protoRegistry struct{}

func (*protoRegistry) UnstableProtoMessageType(name string) (reflect.Type, error) {
	if t := proto.MessageType(name); t != nil {
		return t, nil
	}
	if t := gogo_proto.MessageType(name); t != nil {
		return t, nil
	}
	return nil, nil
}

func (*protoRegistry) UnstableEnumValueMap(name string) map[string]int32 {
	if ev := proto.EnumValueMap(name); ev != nil {
		return ev
	}
	if ev := gogo_proto.EnumValueMap(name); ev != nil {
		return ev
	}
	return nil
}

func main() {

	usage := `envoy-proto: creates an appoptics-style envoy configuration from a skycfg file

Usage:
  envoy-proto <input-file>
  envoy-proto -h | --help

Options:
  <input-file>  skycfg file to be read
  -h --help     Show this screen.`

	arguments, _ := docopt.ParseDoc(usage)

	ctx := context.Background()
	config, err := skycfg.Load(ctx, arguments["<input-file>"].(string), skycfg.WithProtoRegistry(&protoRegistry{}))
	if err != nil {
		panic(err)
	}
	messages, err := config.Main(ctx)
	if err != nil {
		panic(err)
	}
	for _, msg := range messages {
		var jsonMarshaler = &jsonpb.Marshaler{OrigName: true}

		marshaled, err := jsonMarshaler.MarshalToString(msg)
		sep := ""
		var yamlMap yaml.MapSlice
		if err := yaml.Unmarshal([]byte(marshaled), &yamlMap); err != nil {
			panic(fmt.Sprintf("yaml.Unmarshal: %v", err))
		}
		yamlMarshaled, err := yaml.Marshal(yamlMap)
		if err != nil {
			panic(fmt.Sprintf("yaml.Marshal: %v", err))
		}
		marshaled = string(yamlMarshaled)
		sep = "---\n"
		fmt.Printf("%s%s\n", sep, marshaled)
	}
}
```

reproducer/message.sky
```python
pb = proto.package("google.protobuf")
v2_core = proto.package("envoy.api.v2.core")
v2_metrics = proto.package("envoy.config.metrics.v2")

# Common helpers
def _address(ipaddr, port):
    """Returns a v2_core.Address that consists of a single
    v2_core.SocketAddress"""
    return v2_core.Address(
        socket_address=v2_core.SocketAddress(
            address=ipaddr,
            port_value=port))

def _to_struct(msg):
    return proto.from_json(pb.Struct, proto.to_json(msg))
# End of the common helpers

def stats_sink_msg(ip, port):
    sink_address = _address(ip, port)
    sink_address.socket_address.protocol = v2_core.SocketAddress.Protocol.UDP
    ss = v2_metrics.StatsSink(
        name="envoy.dog_statsd",
        config=_to_struct(v2_metrics.DogStatsdSink(address=sink_address)))
    return ss

def main(ctx):
    stats_sinks = [stats_sink_msg("127.0.0.1", 8126)]     
    return [stats_sinks]
```

**Comment by dilyevsky** [comment]
Thanks, @pcn!

Full stack trace:
```
panic: reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*types.Value

goroutine 1 [running]:
reflect.Value.assignTo(0x1861140, 0xc00028af90, 0x15, 0x196b21d, 0xb, 0x1861080, 0x0, 0x100e80d, 0x1925240, 0xc00028af90)
	/usr/local/go/src/reflect/value.go:2269 +0x44c
reflect.Value.Set(0x1861080, 0xc00028aea0, 0x195, 0x1861140, 0xc00028af90, 0x15)
	/usr/local/go/src/reflect/value.go:1403 +0xa7
github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc0001d39a0, 0x18e30e0, 0xc00028aea0, 0x199, 0xc000092780, 0x59, 0x60, 0x0, 0x100dc38, 0x160)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:828 +0x24ed
github.com/golang/protobuf/jsonpb.(*Unmarshaler).UnmarshalNext(0xc0001d39a0, 0xc0000bfb80, 0x2719838, 0xc00028aea0, 0xc0001b6601, 0xc0001d39c0)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:669 +0x195
github.com/golang/protobuf/jsonpb.(*Unmarshaler).Unmarshal(0xc0001d39a0, 0x1a30160, 0xc0001d39c0, 0x2719838, 0xc00028aea0, 0xc00028aea0, 0x193a420)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:680 +0x77
github.com/golang/protobuf/jsonpb.UnmarshalString(0xc000092720, 0x59, 0x2719838, 0xc00028aea0, 0x2, 0x0)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:701 +0xad
github.com/stripe/skycfg/internal/go/skycfg.fnProtoFromJson(0xc00000dd20, 0xc0001668a0, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x30, 0x18e46a0, ...)
	/Users/dilyevsky/go/pkg/mod/github.com/stripe/skycfg@v0.0.0-20181214184926-acf0ed60ad24/internal/go/skycfg/proto_api.go:293 +0x1e1
go.starlark.net/starlark.(*Builtin).CallInternal(0xc0001668a0, 0xc00000dd20, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/value.go:584 +0x8b
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef00, 0xc0001668a0, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x1a3f940, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0002a2810, 0x0, 0xc0001b6e40, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177d50, 0xc00000dd20, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177d50, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1a3ee40, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc0001b7590, 0xc00000e7f8, 0xc0001b7520, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177dc0, 0xc00000dd20, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177dc0, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x110, 0xc00018efc0, 0xc0001b7c00, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177e30, 0xc00000dd20, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1914ea0, 0x1a3ef80, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177e30, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x20, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
github.com/stripe/skycfg.(*Config).Main(0xc00000dd00, 0x1a3bfc0, 0xc000032078, 0x0, 0x0, 0x0, 0x1, 0xc00000dd00, 0x0, 0x0, ...)
	/Users/dilyevsky/go/pkg/mod/github.com/stripe/skycfg@v0.0.0-20181214184926-acf0ed60ad24/skycfg.go:295 +0x3be
main.main()
	/Users/dilyevsky/go/src/github.com/stripe/skycfg/_examples/reproduce/main.go:65 +0x1a7

**Comment by dilyevsky** [comment]
Thanks, @pcn!

Full stack trace:
```
panic: reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*types.Value

goroutine 1 [running]:
reflect.Value.assignTo(0x1861140, 0xc00028af90, 0x15, 0x196b21d, 0xb, 0x1861080, 0x0, 0x100e80d, 0x1925240, 0xc00028af90)
	/usr/local/go/src/reflect/value.go:2269 +0x44c
reflect.Value.Set(0x1861080, 0xc00028aea0, 0x195, 0x1861140, 0xc00028af90, 0x15)
	/usr/local/go/src/reflect/value.go:1403 +0xa7
github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue(0xc0001d39a0, 0x18e30e0, 0xc00028aea0, 0x199, 0xc000092780, 0x59, 0x60, 0x0, 0x100dc38, 0x160)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:828 +0x24ed
github.com/golang/protobuf/jsonpb.(*Unmarshaler).UnmarshalNext(0xc0001d39a0, 0xc0000bfb80, 0x2719838, 0xc00028aea0, 0xc0001b6601, 0xc0001d39c0)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:669 +0x195
github.com/golang/protobuf/jsonpb.(*Unmarshaler).Unmarshal(0xc0001d39a0, 0x1a30160, 0xc0001d39c0, 0x2719838, 0xc00028aea0, 0xc00028aea0, 0x193a420)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:680 +0x77
github.com/golang/protobuf/jsonpb.UnmarshalString(0xc000092720, 0x59, 0x2719838, 0xc00028aea0, 0x2, 0x0)
	/Users/dilyevsky/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:701 +0xad
github.com/stripe/skycfg/internal/go/skycfg.fnProtoFromJson(0xc00000dd20, 0xc0001668a0, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x30, 0x18e46a0, ...)
	/Users/dilyevsky/go/pkg/mod/github.com/stripe/skycfg@v0.0.0-20181214184926-acf0ed60ad24/internal/go/skycfg/proto_api.go:293 +0x1e1
go.starlark.net/starlark.(*Builtin).CallInternal(0xc0001668a0, 0xc00000dd20, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/value.go:584 +0x8b
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef00, 0xc0001668a0, 0xc0001d3940, 0x2, 0x2, 0x0, 0x0, 0x0, 0x1a3f940, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0002a2810, 0x0, 0xc0001b6e40, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177d50, 0xc00000dd20, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177d50, 0xc0002a2ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1a3ee40, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc0001b7590, 0xc00000e7f8, 0xc0001b7520, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177dc0, 0xc00000dd20, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x22a0000, 0x10149c0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177dc0, 0xc00000dd60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
go.starlark.net/starlark.call(0xc00000dd20, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x110, 0xc00018efc0, 0xc0001b7c00, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:287 +0x3ce5
go.starlark.net/starlark.(*Function).CallInternal(0xc000177e30, 0xc00000dd20, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1914ea0, 0x1a3ef80, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/interp.go:36 +0x17d
go.starlark.net/starlark.Call(0xc00000dd20, 0x1a3ef80, 0xc000177e30, 0xc0001594f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x20, ...)
	/Users/dilyevsky/go/pkg/mod/go.starlark.net@v0.0.0-20181108041844-f4938bde4080/starlark/eval.go:857 +0x12a
github.com/stripe/skycfg.(*Config).Main(0xc00000dd00, 0x1a3bfc0, 0xc000032078, 0x0, 0x0, 0x0, 0x1, 0xc00000dd00, 0x0, 0x0, ...)
	/Users/dilyevsky/go/pkg/mod/github.com/stripe/skycfg@v0.0.0-20181214184926-acf0ed60ad24/skycfg.go:295 +0x3be
main.main()
	/Users/dilyevsky/go/src/github.com/stripe/skycfg/_examples/reproduce/main.go:65 +0x1a7
```

Interestingly I don't get the same stack trace with _examples/repl code:

```
error evaluating "../repl/msg.sky": TypeError: value <google.protobuf.Struct fields:<key:"address" value:<struct_value:<fields:<key:"socket_address" value:<struct_value:<fields:<key:"address" value:<string_value:"127.0.0.1" > > fields:<key:"port_value" value:<number_value:8126 > > fields:<key:"protocol" value:<string_value:"UDP" > > > > > > > > > (type `google.protobuf.Struct') can't be assigned to type `google.protobuf.Struct'.
```

Could be a regression in protobuf json unmarshalling code.

**Comment by pcn** [comment]
Is there some documentation on what the purpose of the registry is, and for now how it could be used to resolve this? For the time being, I'm looking at a fair number of structs in further envoy config work, and I'd like to understand if there's a way I could use the registry struct in the `main.go` I've got to resolve this sort of problem, even if it means a lot of special-casing for now.

**Comment by dilyevsky** [comment]
@pcn you can use this workaround for now:

```go
func fnProtoFromJson(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
        var msgType starlark.Value
        var value starlark.String
        if err := starlark.UnpackPositionalArgs("gogo_proto.from_json", args, kwargs, 2, &msgType, &value); err != nil {
                return nil, err 
        }

        name := msgType.(starlark.Callable).Name()
        fmt.Println("Gogo Type: ", name)
        goType := gogo_proto.MessageType(name)
        if goType == nil {
                return nil, fmt.Errorf("TypeError: type `%s' not found", name)
        }

        var emptyMsg descriptor.Message
        if goType.Kind() == reflect.Ptr {
                goValue := reflect.New(goType.Elem()).Interface()
                if iface, ok := goValue.(descriptor.Message); ok {
                        emptyMsg = iface
                }
        }
        if emptyMsg == nil {
                // Return a slightly useful error in case some clever person has
                // manually registered a `proto.Message` that doesn't use pointer
                // receivers.
                return nil, fmt.Errorf("InternalError: %v is not a generated proto.Message", goType)
        }

        msg := proto.Clone(emptyMsg)
        msg.Reset()

        if err := jsonpb.UnmarshalString(string(value), msg); err != nil {
                return nil, err 
        }
        return skycfg.NewProtoMessage(msg), nil 
}

...
// Pass this option into skycfg.Load.
gOpt := skycfg.WithGlobals(starlark.StringDict{"gogo_from_json": starlark.NewBuiltin("gogo_from_json", fnProtoFromJson)})
```

Then in you skycfg:
```python
def _to_struct(msg):
    return gogo_from_json(pb.Struct, proto.to_json(msg))
```
